apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
  name: "default"
spec:
  podPriorityThreshold: ${pod-priority}
  resourceLimits:
    maxNodesTotal: ${max-total-nodes}
    cores:
      min: ${min-cores}
      max: ${max-cores}
    memory:
      min: ${min-memory} 
      max: ${max-memory}
  scaleDown: 
    enabled: ${scaledown-enabled} 
    delayAfterAdd: ${delay-after-add} 
    delayAfterDelete: ${delay-after-delete} 
    delayAfterFailure: ${delay-after-failure} 
    unneededTime: ${unneeded-time}