---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "${clusterid}-worker-${region}1"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "${clusterid}-worker-${region}1"
---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "${clusterid}-worker-${region}2"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "${clusterid}-worker-${region}2"
---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "${clusterid}-worker-${region}3"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "${clusterid}-worker-${region}3"
