---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "${clusterid}-worker-${region}${zone}"
  namespace: "openshift-machine-api"
spec:
  minReplicas: ${workerNodeCount}
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "${clusterid}-worker-${region}${zone}"
