---
- name: Create azurefiles storage class and Cluster role
  hosts: localhost
  gather_facts: no 
  tasks:
  #Create storage class 
  - name: create azure files storage class 
    kubernetes.core.k8s:
      definition: 
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: azurefiles-standard
        provisioner: kubernetes.io/azure-file
        parameters:
          skuName: Standard_LRS
          location: "{{ lookup('env', 'DEPLOY_REGION') }}"
          storageAccount: "masazfilestorageac"
      wait: yes

  #Create cluster role binding 
  - name: create azure files storage class 
    kubernetes.core.k8s:
      definition: 
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          labels:
            subjectName: kube-system-persistent-volume-binder
          name: kube-system-persistent-volume-binder:cluster-admin
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: persistent-volume-binder
          namespace: kube-system
      wait: yes

